# Generated by Django 4.0.1 on 2022-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
