# Generated by Django 4.0.1 on 2022-08-10 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
